[package]
name = "dsplib"
version = "0.2.0"

[lib]
lang = "c++11"

[test]
lang = "c++17"

[[bin]]
name = "dsplib-examples"
path = "examples"
lang = "c++17"

[dev-dependencies]
gtest = { git = "http://github.com/google/googletest.git" }
matplot = { git = "https://github.com/alandefreitas/matplotplusplus.git" }

[options.gtest]
BUILD_GMOCK = false
