[package]
name = "dsplib"
version = "0.6.3"

[lib]
lang = "c++11"

[[test]]
lang = "c++17"

[[test]]
name = "dsplib-examples"
path = "examples"
lang = "c++17"

[dev-dependencies]
gtest = { git = "https://github.com/google/googletest.git" }
matplot = { git = "https://github.com/alandefreitas/matplotplusplus.git" }

[options.gtest]
BUILD_GMOCK = false
gtest_force_shared_crt = true