[package]
name = "dsplib"
version = "0.22.3"

[lib]
lang = "c++11"

[[test]]
lang = "c++17"
name = "dsplib-test"
path = "tests"

[dev-dependencies]
gtest = { git = "https://github.com/google/googletest.git", rev = "release-1.11.0" }

[options.gtest]
BUILD_GMOCK = false
gtest_force_shared_crt = true
