[package]
name = "dsplib"
version = "0.11.0"

[lib]
lang = "c++11"

[[test]]
lang = "c++17"

[[example]]
lang = "c++17"

[dev-dependencies]
gtest = { git = "https://github.com/google/googletest.git", rev = "release-1.11.0" }
matplot = { git = "https://github.com/alandefreitas/matplotplusplus.git" }

[options.gtest]
BUILD_GMOCK = false
gtest_force_shared_crt = true