if (${CMAKE_VERSION} VERSION_GREATER "3.10.0")
    return()
endif()

get_property(__INCLUDE_GUARD_EXIST__ GLOBAL PROPERTY __INCLUDE_GUARD__)
if (__INCLUDE_GUARD_EXIST__)
    return()
endif()
set_property(GLOBAL PROPERTY __INCLUDE_GUARD__ TRUE)

macro(include_guard __SCOPE__)
    if ("${__SCOPE__}" STREQUAL "GLOBAL")
        string(REGEX MATCH "[a-zA-Z0-9\\_\\.-]+\\.cmake" __FNAME__ ${CMAKE_CURRENT_LIST_FILE})
        string(REPLACE ".cmake" "" __FNAME__ ${__FNAME__})
        string(TOUPPER ${__FNAME__} __FNAME__)
        get_property(__SCOPE_EXIST__ GLOBAL PROPERTY ${__FNAME__})
        if (__SCOPE_EXIST__)
            return()
        endif()
        set_property(GLOBAL PROPERTY ${__FNAME__} TRUE)
    else()
        message(ERROR_MESSAGE "include guard scope <${__SCOPE__}> is not supported")
    endif()
endmacro(include_guard)