#!/usr/bin/env python3
# autoplace in .git/hooks/bastard-post-commit

# check version in bastard.toml and generate git tag

import sys, re, subprocess

result = subprocess.run(['git', 'diff', 'HEAD^', 'HEAD', '-U0', '--', 'bastard.toml'], capture_output=True, text=True)
stderr = result.stderr
stdout = result.stdout

if stderr:
    sys.exit(-1)

regex = re.compile('^\+\s?version\s?=\s?"([0-9]+).([0-9]+).([0-9]+)"')
for diff_line in stdout.split("\n"):
    mtch = regex.match(diff_line)
    if mtch:
        ver_major = mtch.group(1)
        ver_minor = mtch.group(2)
        ver_patch = mtch.group(3)
        tag = f"v{ver_major}.{ver_minor}.{ver_patch}"
        result = subprocess.run(['git', 'tag', tag], capture_output=True, text=True)
        if result.stderr:
            sys.exit(-1)
        print(f"Created tag: {tag}")