name: linux-ci

on:
  push:
    paths-ignore: ["README.md"]

  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build-${{matrix.compiler}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DDSPLIB_ASAN_ENABLED=True
        env:
          CXX: ${{matrix.compiler}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build-${{matrix.compiler}} --target dsplib-test

      - name: Test
        working-directory: ${{github.workspace}}/build-${{matrix.compiler}}
        run: ./dsplib-test
